name: Publish to npm

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'

      - name: Susun folder template
        run: |
          mkdir -p template
          EXCLUDES=(
            --exclude='.git'
            --exclude='.github'
            --exclude='node_modules'
            --exclude='package.json'
            --exclude='package-lock.json'
            --exclude='README.md'
            --exclude='bin'
            --exclude='template'
          )
          if [ -f .gitignore ]; then
            EXCLUDES+=(--exclude-from='.gitignore')
          fi
          rsync -a "${EXCLUDES[@]}" ./ template/
          echo "Isi folder template:"
          find template -type f
      - name: set Logo
        run: |
          mkdir -p media
          cp template/media/logomark.png media/logomark.png
      - name: Publish ke npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
